In [55]:
import numpy as np
import pandas as pd
import siuba as sb

flights = pd.read_csv('data/flights.csv')

# para ver los primeros 10 registros
print(flights.head(10))

   year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0  2013      1    1     517.0             515        2.0     830.0
1  2013      1    1     533.0             529        4.0     850.0
2  2013      1    1     542.0             540        2.0     923.0
3  2013      1    1     544.0             545       -1.0    1004.0
4  2013      1    1     554.0             600       -6.0     812.0
5  2013      1    1     554.0             558       -4.0     740.0
6  2013      1    1     555.0             600       -5.0     913.0
7  2013      1    1     557.0             600       -3.0     709.0
8  2013      1    1     557.0             600       -3.0     838.0
9  2013      1    1     558.0             600       -2.0     753.0

   sched_arr_time  arr_delay carrier  flight tailnum origin dest  air_time  \
0             819       11.0      UA    1545  N14228    EWR  IAH     227.0
1             830       20.0      UA    1714  N24211    LGA  IAH     227.0
2             850       33.0      AA    1141  N619AA    JFK  MIA     160.0
3            1022      -18.0      B6     725  N804JB    JFK  BQN     183.0
4             837      -25.0      DL     461  N668DN    LGA  ATL     116.0
5             728       12.0      UA    1696  N39463    EWR  ORD     150.0
6             854       19.0      B6     507  N516JB    EWR  FLL     158.0
7             723      -14.0      EV    5708  N829AS    LGA  IAD      53.0
8             846       -8.0      B6      79  N593JB    JFK  MCO     140.0
9             745        8.0      AA     301  N3ALAA    LGA  ORD     138.0

   distance  hour  minute             time_hour
0      1400     5      15  2013-01-01T10:00:00Z
1      1416     5      29  2013-01-01T10:00:00Z
2      1089     5      40  2013-01-01T10:00:00Z
3      1576     5      45  2013-01-01T10:00:00Z
4       762     6       0  2013-01-01T11:00:00Z
5       719     5      58  2013-01-01T10:00:00Z
6      1065     6       0  2013-01-01T11:00:00Z
7       229     6       0  2013-01-01T11:00:00Z
8       944     6       0  2013-01-01T11:00:00Z
9       733     6       0  2013-01-01T11:00:00Z

In [23]:
flights[flights['arr_delay'] >= 120]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
119,2013,1,1,811.0,630,101.0,1047.0,830,137.0,MQ,4576,N531MQ,LGA,CLT,118.0,544,6,30,2013-01-01T11:00:00Z
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
447,2013,1,1,1505.0,1310,115.0,1638.0,1431,127.0,EV,4497,N17984,EWR,RIC,63.0,277,13,10,2013-01-01T18:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,4294,N13988,EWR,SAV,95.0,708,16,49,2013-09-30T20:00:00Z
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,5292,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30T22:00:00Z
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T22:00:00Z
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z

In [65]:
sb.filter(flights,flights.month==1, flights.day==1)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,2013,1,1,2356.0,2359,-3.0,425.0,437,-12.0,B6,727,N588JB,JFK,BQN,186.0,1576,23,59,2013-01-02T04:00:00Z
838,2013,1,1,NaN,1630,NaN,NaN,1815,NaN,EV,4308,N18120,EWR,RDU,NaN,416,16,30,2013-01-01T21:00:00Z
839,2013,1,1,NaN,1935,NaN,NaN,2240,NaN,AA,791,N3EHAA,LGA,DFW,NaN,1389,19,35,2013-01-02T00:00:00Z
840,2013,1,1,NaN,1500,NaN,NaN,1825,NaN,AA,1925,N3EVAA,LGA,MIA,NaN,1096,15,0,2013-01-01T20:00:00Z
841,2013,1,1,NaN,600,NaN,NaN,901,NaN,B6,125,N618JB,JFK,FLL,NaN,1069,6,0,2013-01-01T11:00:00Z

Es muy raro porque si hago como en los apuntes me da error

In [29]:
flights[flights['dest'].isin(['IAH', 'HOU'])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
32,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,496,N459UA,LGA,IAH,229.0,1416,6,27,2013-01-01T11:00:00Z
81,2013,1,1,728.0,732,-4.0,1041.0,1038,3.0,UA,473,N488UA,LGA,IAH,238.0,1416,7,32,2013-01-01T12:00:00Z
89,2013,1,1,739.0,739,0.0,1104.0,1038,26.0,UA,1479,N37408,EWR,IAH,249.0,1400,7,39,2013-01-01T12:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336524,2013,9,30,1729.0,1720,9.0,2001.0,2010,-9.0,UA,652,N455UA,EWR,IAH,173.0,1400,17,20,2013-09-30T21:00:00Z
336527,2013,9,30,1735.0,1715,20.0,2010.0,2005,5.0,WN,2067,N296WN,EWR,HOU,188.0,1411,17,15,2013-09-30T21:00:00Z
336618,2013,9,30,1859.0,1859,0.0,2134.0,2159,-25.0,UA,1128,N14731,LGA,IAH,180.0,1416,18,59,2013-09-30T22:00:00Z
336694,2013,9,30,2015.0,2015,0.0,2244.0,2307,-23.0,UA,1545,N17730,EWR,IAH,174.0,1400,20,15,2013-10-01T00:00:00Z
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z

In [72]:
flights >> sb.filter((_.dep_delay <= 0) | (_.arr_delay <= 0)) #Da erorr una cosa de los apuntes

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [16]:
flights_sort = flights.sort_values('distance')
flights_sort.head(10)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
275945,2013,7,27,NaN,106,NaN,NaN,245,NaN,US,1632,NaN,EWR,LGA,NaN,17,1,6,2013-07-27T05:00:00Z
3083,2013,1,4,1240.0,1200,40.0,1333.0,1306,27.0,EV,4193,N14972,EWR,PHL,30.0,80,12,0,2013-01-04T17:00:00Z
16328,2013,1,19,1617.0,1617,0.0,1722.0,1722,0.0,EV,4616,N12540,EWR,PHL,34.0,80,16,17,2013-01-19T21:00:00Z
112178,2013,2,1,2128.0,2129,-1.0,2216.0,2224,-8.0,EV,4619,N13969,EWR,PHL,24.0,80,21,29,2013-02-02T02:00:00Z
19983,2013,1,23,2128.0,2129,-1.0,2221.0,2224,-3.0,EV,4619,N12135,EWR,PHL,23.0,80,21,29,2013-01-24T02:00:00Z
11249,2013,1,13,2243.0,2129,74.0,2400.0,2224,96.0,EV,4619,N16963,EWR,PHL,31.0,80,21,29,2013-01-14T02:00:00Z
137872,2013,3,2,1926.0,1929,-3.0,2011.0,2023,-12.0,EV,4457,N21144,EWR,PHL,30.0,80,19,29,2013-03-03T00:00:00Z
116412,2013,2,6,2125.0,2129,-4.0,2207.0,2224,-17.0,EV,4619,N12564,EWR,PHL,28.0,80,21,29,2013-02-07T02:00:00Z
117352,2013,2,7,2145.0,2129,16.0,2234.0,2224,10.0,EV,4619,N16918,EWR,PHL,30.0,80,21,29,2013-02-08T02:00:00Z
13068,2013,1,15,2122.0,2130,-8.0,2207.0,2225,-18.0,EV,4619,N16976,EWR,PHL,26.0,80,21,30,2013-01-16T02:00:00Z

Escogemos los 10 vuelos que recorrieron menor distancia usando siuba

In [50]:
sb.arrange(flights, flights.distance) # no sé solucionar el error

TypeError: 'Series' object is not callable

In [17]:
flights_sort = flights.sort_values('arr_delay', ascending=False)
flights_sort.head(5)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
7072,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,HA,51,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09T14:00:00Z
235778,2013,6,15,1432.0,1935,1137.0,1607.0,2120,1127.0,MQ,3535,N504MQ,JFK,CMH,74.0,483,19,35,2013-06-15T23:00:00Z
8239,2013,1,10,1121.0,1635,1126.0,1239.0,1810,1109.0,MQ,3695,N517MQ,EWR,ORD,111.0,719,16,35,2013-01-10T21:00:00Z
327043,2013,9,20,1139.0,1845,1014.0,1457.0,2210,1007.0,AA,177,N338AA,JFK,SFO,354.0,2586,18,45,2013-09-20T22:00:00Z
270376,2013,7,22,845.0,1600,1005.0,1044.0,1815,989.0,MQ,3075,N665MQ,JFK,CVG,96.0,589,16,0,2013-07-22T20:00:00Z

In [20]:
flights['speed'] = flights['distance'] / flights['air_time'] * 60
flights_sort = flights.sort_values('speed', ascending=False)
flights_sorted.head(1)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
216447,2013,5,25,1709.0,1700,9.0,1923.0,1937,-14.0,DL,1499,N666DN,LGA,ATL,65.0,762,17,0,2013-05-25T21:00:00Z,703.384615

In [51]:
flights_speed = sb.mutate(flights, speed = (flights.distance / flights.air_time) * 60)
flights_sorted = sb.arrange(flights_speed, sb.desc(flights_speed.speed))
flights_sorted.head(1)

print(fastest_flight)

AttributeError: module 'siuba' has no attribute 'desc'

In [ ]:
flights[['dep_time', 'dep_delay', 'arr_time', 'arr_delay']]
flights.loc[:, ['dep_time', 'dep_delay', 'arr_time', 'arr_delay']]
flights.filter(['dep_time', 'dep_delay', 'arr_time', 'arr_delay'])

In [ ]:
flights['dep_time_mins'] = (np.floor(flights['dep_time'] / 100) * 60) + (flights['dep_time'] % 100)
flights['sched_dep_time_mins'] = (np.floor(flights['sched_dep_time'] / 100) * 60) + (flights['sched_dep_time'] % 100)
flights_selected = flights.drop(['dep_time', 'sched_dep_time'], axis=1)

In [ ]:
flights['date'] = pd.to_datetime(flights[['year', 'month', 'day']])
flights_grouped = flights.groupby('date').agg({'dep_time': ['min', 'max']})
flights_grouped.columns = ['first_dep_time', 'last_dep_time']